### ISSUE TITLE
Error when streaming video from Wi-Fi to Ethernet

### ISSUE THREAD

**Issue by sidprice** [david-cermak/eth-ap-nat#1]
I am using the eth-ap-net example to stream some video from a couple of ESP32-CAM boards. I have set the video resolution to 640 x 480 and also reduced the frame rate to 10 fps. I noticed the streaming was stopping after a while, so I first left only one ESP32-CAM streaming to see if that fixed the issue. It improved the issue but still failed.

After attaching a terminal to the serial output of the ESP32-Ethernet Kit I noticed the following error:

`esp.emac: emac_esp32_transmit(229): insufficient TX buffer size`

Once this occurs it happens continuously and the only way to recover is to reset the ESP32-Ethernet board.

I have tried to increase the Ethernet DMA buffer size to 1024, but that did not help.

Can you suggest how to resolve this issue or at least how to have the code recover from the error.

**Comment by sidprice** [comment]
In spite of also increasing the number of TX buffers from 10 to 20 the failure is still happening. As I said before, I am streaming a 10fps with a 640 x 480 resolution, I would expect the device to be able to handle this reliably.

If you can point me in the right direction to try and debug this I would much appreciate it.

**Comment by david-cermak** [comment]
> I am using the eth-ap-net example to stream some video

Are you sending UDP packets only (WiFi to ethernet)? or is also there some communication from ethernet to Wifi?

> Once this occurs it happens continuously and the only way to recover is to reset the ESP32-Ethernet board.

Can you please check if the device ran out of memory (once this occurs)? I would suspect the DMA capable memory, which ethernet interface needs, might get depleted and than the ethernet side to get stuck.


About buffers: Please check the IDF configs for `iperf` examples:

* https://github.com/espressif/esp-idf/tree/master/examples/wifi/iperf
* https://github.com/espressif/esp-idf/tree/master/examples/ethernet/iperf

They are tuned to provide maximum throughput, so setting buffers accordingly might help.

**Comment by sidprice** [comment]
> Are you sending UDP packets only (WiFi to ethernet)? or is also there some communication from ethernet to Wifi?

The video stream is using TCP/IP I think, the final design will have some very low bandwidth UDP (Multicast) messages.

> Can you please check if the device ran out of memory (once this occurs)?

Not sure how to do this, will research.

> ... so setting buffers accordingly might help

Will check those examples out, thanks.

**Comment by sidprice** [comment]
I experimented with buffer numbers and sizes and found that I could not get a stable application running when two ESP32-CAM modules were streaming video. Since this was an experiment for a client, he decided he would go another route. So, I am closing this issue.
