### ISSUE TITLE
esp_event_handler_register in eth-ap-L2

### ISSUE THREAD

**Issue by mmrein** [david-cermak/eth-ap-nat#2]
Hello David, first off, thank you for this set of very helpful examples. Using principles from https://github.com/david-cermak/eth-ap-nat/blob/main/eth-ap-L2 I am successfully forwarding ethernet packets to mesh while the root node also has web UI on it.

But I have slight issue with use of **[esp_eth_set_default_handlers()](https://github.com/david-cermak/eth-ap-nat/blob/b72122195f8788606397fda645de3c6a9fdc482c/eth-ap-L2/main/ethernet_example_main.c#L360)** which is marked as deprecated in IDF v4.4 and is removed in v5.0. The docs and [migration guide](https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32/migration-guides/release-5.x/networking.html#esp-netif-glue-event-handlers) says it should not be needed if correctly initialized, but it is not clear to me how to do this - without it I can't reach the root's web UI. **Any ideas what the issue could be?**

Now I'm on IDF v4.4.4 and probably will keep using it for a while (mainly because of ESP-MDF) so it is not a big of a deal right now, but at some point I will most likely have so switch to v5+.

**Comment by david-cermak** [comment]
Hi @mmrein 

This function was deprecated just to simplify IDF's Ethernet driver initialization, now it's called internally in the default config (basic connection to TCP/IP stack). This example doesn't use the default netif glue, but needs to connect to TCP/IP at some point:

https://github.com/david-cermak/eth-ap-nat/blob/b72122195f8788606397fda645de3c6a9fdc482c/eth-ap-L2/main/ethernet_example_main.c#L359-L360

To make it work without the default handlers (in `v5.0`), you could either reuse the netif glue, or define your own Ethernet handlers. The second option is probably easier (but depends on your project and network settings), just need to connect Ethernet events with network actions:
* `ETHERNET_EVENT_START` -> `esp_netif_action_start()`
* `ETHERNET_EVENT_STOP` -> `esp_netif_action_stop()`
* `ETHERNET_EVENT_CONNECTED` -> `esp_netif_action_connected()`
* `ETHERNET_EVENT_DISCONNECTED` -> `esp_netif_action_disconnected()`

you can use:
```cpp
    auto ret = esp_event_handler_register(ETH_EVENT, $event, $action, eth_netif);
```
To connect it together the same way this demo-example does, or per your own project preferences (e.g. at which point you'd like to start network...)

**Comment by mmrein** [comment]
Ok, so I've literally replaced the default_handlers func with following:

```c
ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ETHERNET_EVENT_START, esp_netif_action_start, eth_netif));
ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ETHERNET_EVENT_STOP, esp_netif_action_stop, eth_netif));
ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ETHERNET_EVENT_CONNECTED, esp_netif_action_connected, eth_netif));
ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ETHERNET_EVENT_DISCONNECTED, esp_netif_action_disconnected, eth_netif));
```

And it works, simple as that :) Thank you, @david-cermak .
